FROM python:3.12

WORKDIR /usr/src/app

COPY requirements.txt requirements.dev.txt /usr/src/app/
RUN pip install -r requirements.txt -r requirements.dev.txt

ENTRYPOINT ["gunicorn", "-b", "0.0.0.0:8000", "deezer_assignement.wsgi"]