# Generated by Django 5.0.3 on 2024-03-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_user_users_user_email_6f2530_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fib',
            field=models.BigIntegerField(),
        ),
    ]
