# Generated by Django 5.0.3 on 2024-03-23 20:17

from django.db import migrations, models

import users.models.user


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_name_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    users.models.user.validate_deezer_email,
                    users.models.user.prohibit_upper_case_chars,
                ],
            ),
        ),
    ]
