# Generated by Django 5.0.3 on 2024-03-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_fib'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_6f2530_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='fib',
            field=models.BigIntegerField(null=True),
        ),
    ]
