name: Backend

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

defaults:
  run:
    working-directory: backend

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Django dependencies
      run: pip install -r requirements.txt -r requirements.dev.txt
        
    - name: lint
      run: |
        black --check .
        isort -c .

    - name: test
      run: DJANGO_DEBUG=true coverage run --rcfile=coverage.rc manage.py test --settings=deezer_assignement.test_settings

    - name: coverage
      run: coverage report  --rcfile=coverage.rc  -m --fail-under=100
