name: Deploy
on:
  push:
    branches:
      - main
      - premain

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Output tag
      run: echo  ${{ steps.filter.outputs.tag }}

    - name: exit
      run: exit 1
        

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REPO }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: cd frontend && npm install

    - name: Build frontend
      run: cd frontend && npm run build

    - name: Copy frontend to django static folder
      run: |
        mkdir -p backend/static/
        mv frontend/dist/* backend/static/

    - name: Set tag
      run: echo "tag=$(echo ${{ steps.meta.outputs.tags }} | tr ',' '\n' | sort -V | tail -n 1)" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        name: reda_bourial_deezer_assignement
        tags: ${{ steps.filter.outputs.tag }}
